driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/trusty64
  - name: ubuntu/xenial64
  - name: centos/7

suites:
  - name: default
    run_list:
      - recipe[cop_base::default]
      - recipe[cop_php::default]
    attributes:
      php:
        ext:
          xdebug:
            enable: true
