driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04.1
    driver:
      box: ubuntu-16.04.1
      box_url: https://s3.amazonaws.com/copiousdev/vagrant/ubuntu-16.04-xenial.box

suites:
  - name: default
    run_list: cop_php::default
